name: Deploy to Production

on:
  # Trigger on push or pull request events to main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allow manual triggering from Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v2

      - name: Deploy to Production Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: node22-ca.n0c.com
          username: Prestataire@senousolutions.com
          password: Prestataire@10
